### ISSUE TITLE
Fuente?

### ISSUE THREAD

**Issue by marcelino-m** [pviojo/transantiago-api#1]
Hola hola!!, donde obtuviste la información de la existencia  del  servicio Rest que ocupas?

PD: Hace un tiempo  implemente una pequeña  herramienta para obtener información relacionada, 
ya que no encontre nada parecido al servicio rest que ocuaps (https://github.com/dinoshunter/transantiago-client),  basicamente hago un scraping de m.ibus.cl

Saludos

**Comment by pviojo** [comment]
Hola, lo encontré revisando el sitio del transantiago (www.transantiago.cl) 

En src/Transantiago/Transantiago.php puedes ver el detalle de las urls usadas.

**Comment by marcelino-m** [comment]
Si, he mirado  y funcionan,  pero por mas que miro la pagina no doy con el links o algo así, 
Ahora no se si soy ciego o tonto XD.

Saludos y gracias por tu respuesta.

**Comment by pviojo** [comment]
No están visibles pero las puedes ver si inspeccionas los requests que se hacen.

Son estos:

```
Ver proximo servicio de un paradero y bus:
http://www.transantiago.cl/predictor/prediccion?codsimt=<codigo paradero>&codser=<codigo servicio>

Ver paraderos cercanos:
http://www.transantiago.cl/restservice/rest/getpuntoparada?lat=<latitud>&lon=<longitud>&bip=1

Ver todo el recorrido:
http://www.transantiago.cl/restservice/rest/getrecorrido/<codigo servicio>

Donde:

<codigo paradero>: Código que tiene cada paradero. Ej: PA435
<codigo servicio>: El número del servicio. Ej: 401
```
